/**
 * src/orchestrator/config.ts — merges the user-editable budget
 * (`config/bot.json`, committed) with the discovered dungeon economics
 * (`config/discovered.json`, generated by `scripts/probe.ts`, gitignored).
 *
 * Fails closed if either is missing rather than falling back to a guessed
 * number — CLAUDE.md §1, "discover, don't assume."
 */

import { existsSync, readFileSync } from "node:fs";
import { z } from "zod";

const BotJsonSchema = z.object({
  forbiddenWoods: z.object({
    dailyEnergyBudget: z.number().positive(),
    maxRunsPerSession: z.number().int().positive(),
    // Session 17: explicit user opt-in required before the live loop uses
    // ANY potion — absent, no potions are used, full stop. Prevents the
    // loop from auto-consuming a limited/valuable consumable it merely
    // finds in inventory without the user having actually authorized it,
    // per the user's direct instruction this session.
    potions: z
      .object({
        allowedItemId: z.number().int().positive(),
        maxPerRun: z.number().int().positive(),
      })
      .optional(),
    // [session 56] The user's boon directive (`src/strategy/boonPriority.ts`).
    // NOT a gate — the directive is ON in live play whether or not this block
    // exists, because it is the user's instruction about how to play rather
    // than a measurement that costs run quality. (A gated sibling schema entry
    // for such a measurement sat directly above until session 96; QUESTIONS.md
    // §37 records it.) This block only lets the one number in it be read
    // without a code change. Absent means the shipped default (rooms 1..8).
    //
    // [session 58] `orbRule` MUST be listed here even though it has a code
    // default: zod strips unknown keys silently, so an unlisted knob would
    // read as absent and setting it to "tie-break" to revert session 58's
    // change would do nothing at all — a config that lies rather than fails.
    boonPriority: z
      .object({
        earlyGameMaxRoom: z.number().int().positive(),
        orbRule: z.enum(["tie-break", "wide"]).optional(),
      })
      .optional(),
  }),
  dendren: z
    .object({
      dailyEnergyBudget: z.number().positive(),
      maxCastsPerSession: z.number().int().positive(),
      // [session 61 §4c] Oils, mirroring `forbiddenWoods.potions`: the user
      // sets the budget, the bot spends within it autonomously and stops. The
      // THIRD field has no potions analogue and is the important one —
      // `policyApproved` is CLAUDE.md rule 4's gate, false until the user has
      // approved a derived timing policy. Absent block = no oil ever spent.
      oils: z
        .object({
          allowedItemIds: z.array(z.number().int().positive()).min(1),
          maxPerCast: z.number().int().positive().max(3),
          // [session 69 §4] Per-item ceiling, keyed by item id as a string.
          // Absent id = no per-item cap ("Focus: unconstrained"), which is
          // deliberately expressed by silence rather than by a number.
          perItemMaxPerCast: z.record(z.string(), z.number().int().nonnegative().max(3)).optional(),
          policyApproved: z.boolean(),
          // [session 113] USER DIRECTIVE 2026-08-30: *"focus oil will not be
          // added back on the allowlist, disable the override rule."* The
          // double-lethal band (QUESTIONS §30, user override 2026-08-24) is
          // OFF, leaving only the rule-4-approved on-demand policy under its
          // necessity gate.
          //
          // **Absent means DISABLED, and that is the point of the shape.**
          // The field is optional and the live path tests `=== true`, so the
          // default behaviour is on-demand-only rather than "off unless
          // configured" — a config file that forgets this key gets the
          // approved policy, never the overridden one. That is the opposite
          // default from `perItemMaxPerCast`, where absence means uncapped,
          // and the difference is deliberate: a missing ceiling can only
          // fail toward spending less, a missing override switch would fail
          // toward spending more.
          doubleLethalOverride: z.boolean().optional(),
        })
        .optional(),
    })
    .optional(),
  guards: z.object({
    maxConsecutiveActionFailures: z.number().int().positive(),
  }),
});

const DiscoveredJsonSchema = z.object({
  forbiddenWoods: z.object({
    id: z.number(),
    energyCost: z.number().positive(),
    maxRoom: z.number().int().positive(),
    maxRunsPerDay: z.number().int().positive(),
  }),
  dendren: z
    .object({
      nodeId: z.string(),
      pondId: z.number(),
      gridSize: z.number(),
      tiers: z.record(
        z.string(),
        z.object({ name: z.string(), energyCost: z.number().positive() }).passthrough(),
      ),
      maxCastsPerDay: z.number().int().positive(),
    })
    .optional(),
});

export interface BotConfig {
  dungeonId: number;
  energyCostPerRun: number;
  maxRoom: number;
  maxRunsPerDayGame: number;
  dailyEnergyBudget: number;
  maxRunsPerSession: number;
  maxConsecutiveActionFailures: number;
  /** User-authorized potion, session 17 — absent means "no potions," not "figure it out from inventory." */
  potions?: { allowedItemId: number; maxPerRun: number };
  /**
   * [session 56] The lifesteal demotion window. Absent means
   * `boonPriority.ts`'s shipped `EARLY_GAME_MAX_ROOM` (8, user-confirmed).
   * Not a gate — see the schema comment.
   */
  boonPriority?: { earlyGameMaxRoom: number; orbRule?: "tie-break" | "wide" };
  dendren?: {
    nodeId: string;
    tierId: number;
    energyCostPerCast: number;
    maxCastsPerDayGame: number;
    dailyEnergyBudget: number;
    maxCastsPerSession: number;
    /** [session 61 §4c] User-authorized oils — absent means "no oils", not "work it out from inventory." */
    oils?: {
      allowedItemIds: number[];
      maxPerCast: number;
      /** [session 69 §4] Per-item per-cast ceiling, keyed by item id as a string. Absent id = uncapped. */
      perItemMaxPerCast?: Record<string, number>;
      policyApproved: boolean;
      /**
       * [session 113] QUESTIONS §30's double-lethal band. **Absent or false =
       * DISABLED**, which is the shipped default per the user directive of
       * 2026-08-30. Only an explicit `true` re-arms it.
       */
      doubleLethalOverride?: boolean;
    };
  };
}

export class MissingConfigError extends Error {
  constructor(path: string, hint: string) {
    super(`Missing config file: ${path}\n${hint}`);
    this.name = "MissingConfigError";
  }
}

export function loadBotConfig(
  botJsonPath = "config/bot.json",
  discoveredJsonPath = "config/discovered.json",
): BotConfig {
  if (!existsSync(botJsonPath)) {
    throw new MissingConfigError(botJsonPath, "This file is committed — it should exist. Check you're in the repo root.");
  }
  if (!existsSync(discoveredJsonPath)) {
    throw new MissingConfigError(
      discoveredJsonPath,
      "Generated by `npm run probe` — it's gitignored and must be produced locally before any live run.",
    );
  }

  const bot = BotJsonSchema.parse(JSON.parse(readFileSync(botJsonPath, "utf8")));
  const discovered = DiscoveredJsonSchema.parse(JSON.parse(readFileSync(discoveredJsonPath, "utf8")));

  // Dendren is optional on both sides — a repo that hasn't run Task 7/9 yet
  // (or a discovered.json predating the dendren block) still gets a valid
  // dungeon-only BotConfig, per this file's own fail-closed-per-feature
  // convention rather than a monolithic all-or-nothing parse.
  let dendren: BotConfig["dendren"];
  if (discovered.dendren && bot.dendren) {
    const tier1 = discovered.dendren.tiers["1"];
    if (!tier1) {
      throw new MissingConfigError(discoveredJsonPath, "dendren.tiers['1'] (the free tier) is missing — re-run Task 7's discovery.");
    }
    dendren = {
      nodeId: discovered.dendren.nodeId,
      tierId: 1,
      energyCostPerCast: tier1.energyCost,
      maxCastsPerDayGame: discovered.dendren.maxCastsPerDay,
      dailyEnergyBudget: bot.dendren.dailyEnergyBudget,
      maxCastsPerSession: bot.dendren.maxCastsPerSession,
      oils: bot.dendren.oils,
    };
  }

  return {
    dungeonId: discovered.forbiddenWoods.id,
    energyCostPerRun: discovered.forbiddenWoods.energyCost,
    maxRoom: discovered.forbiddenWoods.maxRoom,
    maxRunsPerDayGame: discovered.forbiddenWoods.maxRunsPerDay,
    dailyEnergyBudget: bot.forbiddenWoods.dailyEnergyBudget,
    maxRunsPerSession: bot.forbiddenWoods.maxRunsPerSession,
    maxConsecutiveActionFailures: bot.guards.maxConsecutiveActionFailures,
    potions: bot.forbiddenWoods.potions,
    boonPriority: bot.forbiddenWoods.boonPriority,
    dendren,
  };
}
