/**
 * src/orchestrator/config.ts — merges the user-editable budget
 * (`config/bot.json`, committed) with the discovered dungeon economics
 * (`config/discovered.json`, generated by `scripts/probe.ts`, gitignored).
 *
 * Fails closed if either is missing rather than falling back to a guessed
 * number — CLAUDE.md §1, "discover, don't assume."
 */

import { existsSync, readFileSync } from "node:fs";
import { z } from "zod";

const BotJsonSchema = z.object({
  forbiddenWoods: z.object({
    dailyEnergyBudget: z.number().positive(),
    maxRunsPerSession: z.number().int().positive(),
  }),
  guards: z.object({
    maxConsecutiveActionFailures: z.number().int().positive(),
  }),
});

const DiscoveredJsonSchema = z.object({
  forbiddenWoods: z.object({
    id: z.number(),
    energyCost: z.number().positive(),
    maxRoom: z.number().int().positive(),
    maxRunsPerDay: z.number().int().positive(),
  }),
});

export interface BotConfig {
  dungeonId: number;
  energyCostPerRun: number;
  maxRoom: number;
  maxRunsPerDayGame: number;
  dailyEnergyBudget: number;
  maxRunsPerSession: number;
  maxConsecutiveActionFailures: number;
}

export class MissingConfigError extends Error {
  constructor(path: string, hint: string) {
    super(`Missing config file: ${path}\n${hint}`);
    this.name = "MissingConfigError";
  }
}

export function loadBotConfig(
  botJsonPath = "config/bot.json",
  discoveredJsonPath = "config/discovered.json",
): BotConfig {
  if (!existsSync(botJsonPath)) {
    throw new MissingConfigError(botJsonPath, "This file is committed — it should exist. Check you're in the repo root.");
  }
  if (!existsSync(discoveredJsonPath)) {
    throw new MissingConfigError(
      discoveredJsonPath,
      "Generated by `npm run probe` — it's gitignored and must be produced locally before any live run.",
    );
  }

  const bot = BotJsonSchema.parse(JSON.parse(readFileSync(botJsonPath, "utf8")));
  const discovered = DiscoveredJsonSchema.parse(JSON.parse(readFileSync(discoveredJsonPath, "utf8")));

  return {
    dungeonId: discovered.forbiddenWoods.id,
    energyCostPerRun: discovered.forbiddenWoods.energyCost,
    maxRoom: discovered.forbiddenWoods.maxRoom,
    maxRunsPerDayGame: discovered.forbiddenWoods.maxRunsPerDay,
    dailyEnergyBudget: bot.forbiddenWoods.dailyEnergyBudget,
    maxRunsPerSession: bot.forbiddenWoods.maxRunsPerSession,
    maxConsecutiveActionFailures: bot.guards.maxConsecutiveActionFailures,
  };
}
