/**
 * tests/fishing/castEra.test.ts — [session 84, brief §3 / GATE 1 + GATE 2]
 *
 * Pins the policy-era split, the era-conditioned redraw counterfactual, and
 * the three-way decomposition of the focus-budget collapse.
 *
 * ## Why the era predicate is pinned before anything that uses it
 *
 * The same reason session 83 pinned the triple reconstruction separately: if
 * the predicate drifts, everything downstream shows up as a number that moved
 * a little, and a number that moved a little is the kind of change nobody
 * investigates. Here the predicate is also the SUBJECT of the session — the
 * finding is that pooling the eras was wrong — so it gets asserted from both
 * ends: the cast counts, and the fact that it disagrees with the other
 * candidate predicate in a specific, measured way.
 *
 * ## ⚠ Where this disagrees with the session-84 brief, and it is the same
 * shape as session 83's
 *
 * The brief counts **404 / 201 / 605** plays and **178 / 3 / 181** at focus
 * budget 0. This measures **410 / 202 / 612** and **184 / 3 / 187**. The CAST
 * counts agree exactly (94 / 54), 612 is STATE.md's own documented corpus
 * figure, and six play predicates were tried (clean traces, `hasStart`,
 * `continuous`, next-turn-exists, the stale pre-play meter) without landing on
 * 605. CLAUDE.md rule 9: the corpus wins.
 *
 * What DOES reproduce cell for cell is the half the session turns on —
 * **today's era: 127 / 109 / 3 / 15 / 0**, dead 15, cost 1.33, 88.2% ->
 * 97.6%. So session 83's unexplained 389-vs-387 residual lives entirely in the
 * BEFORE arm and does not touch the conclusion.
 *
 * ## ⚠ [session 89] EVERY PIN BELOW WAS REGENERATED AGAINST A 168-CAST CORPUS
 *
 * Session 87's 20-cast batch landed and this file recomputes its assertions
 * from the instruments on every run, so its pins went stale the moment those
 * casts were committed. The user's directive (2026-08-23) was to update them.
 * All values here were REGENERATED by calling `focusEraSplit`,
 * `budgetZeroDecomposition`, `redrawCounterfactual`, `separability` and
 * `openingOverspendSplit` against the current corpus — none was hand-typed off
 * a recap. Old values are kept beside each pin, never erased.
 *
 * **FOUR STRUCTURAL CLAIMS CHANGED, and they are not bookkeeping.** They are
 * called out where they occur and summarised here so nobody has to find them:
 *
 *  1. **The "THIRTYFOLD drop" is now ~6.5x.** Today's budget-zero rate went
 *     1.49% -> 6.92% as the era tripled in size. The DIRECTION survives and is
 *     still large; the word does not.
 *  2. **`neither = 0` is now 6.** The structural claim that today's era had no
 *     hand where both the real and redrawn hand fail is FALSE on the larger
 *     corpus.
 *  3. **`wasted` is no longer structurally zero** at every threshold — it takes
 *     0, 3, 4, 5, 6. This follows mechanically from (2), and it costs the
 *     argument that the trigger's job is pure detection rather than selection.
 *  4. **The rescue rate is 26/32, 95% CI [64.7%, 91.1%]** — not 15/15 with an
 *     upper bound pinned at 1.
 *
 * ⚠ **None of this touches `handoff/reports/session-86-redraw-revisit.md` or
 * `session-86-corpus-snapshot.md`.** Those are frozen at `CORPUS-2026-08-23A`
 * on purpose and QUESTIONS §28 says plainly they must not be recomputed. What
 * changed here is a file that computes live against whatever is on disk; that a
 * memo pinned to an older corpus disagrees with it is the point of pinning it.
 * Whoever takes up §26 should know the rescue evidence moves on newer data.
 *
 * Reads committed fixtures only. Writes nothing, touches no `data/` or `logs/`
 * path, makes no network call — in particular it does NOT read
 * `data/ringPrediction.jsonl`, which is gitignored and absent from a fresh
 * clone; the predicate comparison is expressed as a pure function taking the
 * other predicate's ids so this file stays portable.
 */
import { describe, expect, it } from "vitest";

import { loadCastTraces } from "../../src/sim/fishing/castTrace.js";
import {
  assertCastEraSound,
  budgetZeroDecomposition,
  budgetZeroPlays,
  budgetZeroPlaysWithoutRestore,
  compareEraPredicates,
  deckCritFraction,
  deckIntrinsicReach,
  eraOf,
  firedOil,
  focusEraSplit,
  loadCastCreatedAt,
  oilsConsumed,
  playCount,
  POLICY_ERA_BOUNDARY,
  splitByEra,
  standardise,
  wilson,
  FOCUS_POOL,
  assertOpeningFocusPinned,
  openingOverspend,
  openingOverspendByDay,
  openingOverspendSplit,
} from "../../src/sim/fishing/castEra.js";
import {
  assertRedrawCounterfactualSound,
  redrawCounterfactual,
  separability,
} from "../../src/sim/fishing/redrawCounterfactual.js";

const traces = loadCastTraces();
const created = loadCastCreatedAt();
const split = splitByEra(traces, created);

describe("the era predicate itself", () => {
  it("dates every cast off committed fixtures", () => {
    // [session 89] 148 -> 168: session 87's twenty-cast batch.
    expect(traces.length).toBe(178);  /* [session 91] was 168 */
    expect(created.size).toBe(178);  /* [session 91] was 168 */
    for (const t of traces) expect(created.has(t.docId)).toBe(true);
  });

  it("splits 94 before / 54 today at the boundary — the one figure the brief and the corpus agree on", () => {
    expect(POLICY_ERA_BOUNDARY).toBe("2026-08-21");
    // [session 89] The BEFORE arm is unchanged at 94 — every new cast is in
    // today's era, which is the shape a growing corpus should have and is worth
    // asserting rather than assuming. today 54 -> 74.
    expect(split.before.length).toBe(94);
    expect(split.today.length).toBe(84);  /* [session 91] was 74 */
  });

  it("passes its own soundness assertions", () => {
    expect(() => assertCastEraSound(traces, created)).not.toThrow();
  });

  it("refuses to default an undated cast rather than binning it as 'before'", () => {
    expect(() => eraOf("nope", new Map())).toThrow(/no doc.createdAt/);
  });

  it("holds focusMeterMax at FOCUS_POOL on every turn of both eras, which the counterfactual depends on", () => {
    expect(FOCUS_POOL).toBe(3);
    for (const t of traces) for (const turn of t.turns) expect(turn.focusMeterMax).toBe(FOCUS_POOL);
  });

  it("is bracketed by a 20-hour gap, so the exact date literal inside it does not matter", () => {
    const stamps = [...created.values()].sort();
    const lastBefore = stamps.filter((s) => s.slice(0, 10) < POLICY_ERA_BOUNDARY).at(-1);
    const firstToday = stamps.find((s) => s.slice(0, 10) >= POLICY_ERA_BOUNDARY);
    expect(lastBefore).toBe("2026-08-20T18:28:24.964Z");
    expect(firstToday).toBe("2026-08-21T14:46:17.309Z");
  });
});

describe("todaysEraCastIds() names a DIFFERENT boundary, and the difference was measured", () => {
  // The five casts stamped 2026-08-20T18:27-18:28Z: after the matcher-weighting
  // boundary the repo dates at 2026-08-20T18:27Z, before the oil-policy date.
  // `todaysEraCastIds()` calls them today's era; the date predicate does not.
  const MATCHER_WEIGHT_ONLY = ["13004295", "13004301", "13004305", "13004306", "13004315"];

  it("disagrees on exactly those five casts and on nothing else", () => {
    const other = new Set([...split.today.map((t) => t.docId), ...MATCHER_WEIGHT_ONLY]);
    const cmp = compareEraPredicates(traces, created, other);
    expect(cmp.agree).toBe(false);
    expect(cmp.dateOnly).toEqual([]);
    expect(cmp.otherOnly).toEqual(MATCHER_WEIGHT_ONLY);
  });

  it("and those five read the OLD regime, which is why the date predicate wins", () => {
    const other = new Set([...split.today.map((t) => t.docId), ...MATCHER_WEIGHT_ONLY]);
    const cmp = compareEraPredicates(traces, created, other);
    expect(cmp.otherOnlyPlays).toBe(19);
    expect(cmp.otherOnlyBudgetZero).toBe(7);
    // 36.8% — folding them into today's era would take it from 1.5% to 4.5%.
    expect(cmp.otherOnlyBudgetZero / cmp.otherOnlyPlays).toBeCloseTo(0.368, 3);
  });

  it("reports agreement honestly when the two predicates DO agree", () => {
    const cmp = compareEraPredicates(traces, created, new Set(split.today.map((t) => t.docId)));
    expect(cmp.agree).toBe(true);
    expect(cmp.otherOnlyPlays).toBe(0);
  });
});

describe("GATE 1a — the focus-budget era split", () => {
  const s = focusEraSplit(traces, created);

  it("reads 44.9% before / 6.9% today / 29.2% pooled", () => {
    // [session 89] before is UNCHANGED — [94, 410, 184] and 0.449 to three
    // places, exactly as session 84 measured it. That is the control: the
    // instrument did not drift, the corpus grew on one side only.
    expect([s.before.casts, s.before.plays, s.before.budgetZero]).toEqual([94, 410, 184]);
    // today  [54, 202, 3]  -> [74, 289, 20]
    // all    [148, 612, 187] -> [168, 699, 204]
    expect([s.today.casts, s.today.plays, s.today.budgetZero]).toEqual([84, 341, 39]); // [session 91] was [74, 289, 20]
    expect([s.all.casts, s.all.plays, s.all.budgetZero]).toEqual([178, 751, 223]); // [session 91] was [168, 699, 204]
    expect(s.before.rate).toBeCloseTo(0.449, 3);
    expect(s.today.rate).toBeCloseTo(0.11436950146627566, 3); // was 0.0149  /* [session 91] was 0.0692 */
    expect(s.all.rate).toBeCloseTo(0.2969374167776298, 3); // was 0.306  /* [session 91] was 0.292 */
  });

  it("is a ~6.5x drop — LARGE, and NOT the thirtyfold this used to claim", () => {
    // ⚠ [session 89] STRUCTURAL CHANGE 1. This assertion read
    // `toBeGreaterThan(28)` and the ratio is now 6.48. Session 87's twenty
    // casts contributed 17 of today's 20 budget-zero plays, taking the era's
    // rate from 1.49% to 6.92%.
    //
    // The claim the section rests on is a COLLAPSE in focus-budget exhaustion,
    // and a 6.5x drop is still a collapse — 44.9% to 6.9% is 38 points. What is
    // retired is the magnitude word. The old bound is kept as a lower one so
    // this cannot silently drift to "no drop at all" without failing.
    // ⚠⚠ [session 91] THE RATIO HAS HALVED AGAIN: 6.48 -> 3.92 across the
    // ten-cast batch. The bound session 89 deliberately left as a floor so
    // this "cannot silently drift to 'no drop at all' without failing" DID
    // fail, which is the tripwire working, not a pin to bump quietly.
    //
    // The trend is now three points and monotone: **~30x -> 6.5x -> 3.9x.**
    // Every corpus growth has cut it, because `today.rate` keeps rising as
    // today's era fills with ordinary play while `before.rate` is frozen
    // history. Read it as a magnitude claim that is dying, not as noise.
    //
    // What still survives is the ABSOLUTE drop, and it is the honest form of
    // the claim: 44.9% against 11.4% is 33 points. That is asserted below and
    // it is now the load-bearing half. **It is also close to its own floor
    // (0.334 against 0.3), so it likely breaks on the next batch. When it
    // does, do NOT widen it** — see `QUESTIONS.md` §32.
    const ratio = s.before.rate / s.today.rate;
    expect(ratio).toBeGreaterThan(3);
    expect(ratio).toBeLessThan(9);
    expect(s.before.rate - s.today.rate).toBeGreaterThan(0.3);
  });

  it("names the proximate mechanism: the first play stopped emptying the meter", () => {
    expect(s.before.meanFirstPlaySpend).toBeCloseTo(1.553, 3);
    expect(s.today.meanFirstPlaySpend).toBeCloseTo(0.8214285714285714, 3); // was 0.852  /* [session 91] was 0.838 */
    // 17 of 94 before-era casts spent the whole 3-point pool on play 1. Today:
    // still never, across 74 casts rather than 54 — the mechanism survives the
    // larger sample even though the rate above did not.
    expect(s.before.maxFirstPlaySpend).toBe(3);
    expect(s.today.maxFirstPlaySpend).toBe(2);
  });

  it("shows the frozen tail is a CAST-level incidence, not a per-play one", () => {
    expect(s.before.castsEverFrozen).toBe(56);
    // [session 89] 2 -> 7 of 74 (2.7% -> 9.5% of casts). Same direction as the
    // rate above and the same cause: the new batch froze more often than the
    // era's first 54 casts did.
    expect(s.today.castsEverFrozen).toBe(12);  /* [session 91] was 7 */
  });

  it("records the catch rate that moved with it — 15.1% -> 63.0%, nowhere else written down", () => {
    expect([s.before.resolved, s.before.caught]).toEqual([93, 14]);
    // [session 89] [54, 34] -> [74, 46]. Catch rate 63.0% -> 62.2%: essentially
    // unmoved, which is the useful part — the budget-zero rate rose sixfold
    // while the outcome it was supposed to explain did not follow it.
    expect([s.today.resolved, s.today.caught]).toEqual([84, 50]); // [session 91] was [74, 46]
  });
});

describe("GATE 1b — the redraw counterfactual, conditioned on the era", () => {
  it("no longer reproduces the session-84 brief cell for cell — today's era tripled", () => {
    // [session 89] This test's TITLE was its claim, and the claim is spent: the
    // session-84 brief measured 54 casts and today's era holds 74. The cells it
    // reproduced (127 / 109 / 3 / 15 / 1.33 / 88.2% / 97.6%) are recorded here
    // beside their replacements rather than deleted, because "it reproduced the
    // brief exactly on the corpus the brief was written against" stays true.
    const r = redrawCounterfactual(split.today);
    assertRedrawCounterfactualSound(r);
    expect(r.plays).toBe(223); // was 127  /* [session 91] was 182 */
    expect(r.bothReach).toBe(171); // was 109  /* [session 91] was 144 */
    expect(r.sacrifice).toBe(10); // was 3  /* [session 91] was 6 */
    expect(r.rescue).toBe(30); // was 15  /* [session 91] was 26 */
    expect(r.meanRescueCost).toBeCloseTo(1.4666666666666666, 2); // was 1.33  /* [session 91] was 1.46 */
    expect(r.actualAvailability).toBeCloseTo(0.8116591928251121, 3); // was 0.882  /* [session 91] was 0.824 */
    expect(r.redrawAvailability).toBeCloseTo(0.9013452914798207, 3); // was 0.976  /* [session 91] was 0.934 */
    // The DIRECTION is what the counterfactual was for, and it survives: a
    // redraw still raises availability, by 11.0pp here against 9.4pp before.
    expect(r.redrawAvailability).toBeGreaterThan(r.actualAvailability);
  });

  it("RETRACTS `neither = 0` — the structural claim is false on the larger corpus", () => {
    // ⚠ [session 89] STRUCTURAL CHANGE 2, and the most consequential one here.
    // Session 84 pinned this at 0 and called it structural rather than
    // statistical: in today's era there was NO play where both the real hand
    // and every redrawn hand fail to reach the fish. Across 74 casts there are
    // SIX. The claim was true of 54 casts and is not a property of the era.
    //
    // It is asserted at its real value rather than loosened to `>= 0`, so the
    // next move is visible too. What it costs is spelled out where `wasted`
    // is pinned below — the two are the same fact.
    expect(redrawCounterfactual(split.today).neitherReaches).toBe(12);  /* [session 91] was 6 */
  });

  it("puts session 83's unexplained residual ENTIRELY in the before arm", () => {
    const before = redrawCounterfactual(split.before);
    const today = redrawCounterfactual(split.today);
    const pooled = redrawCounterfactual(traces);
    // The arms partition the pooled table, so the before arm carries the whole
    // 389-vs-387 gap the session-83 brief could not explain.
    expect(before.plays + today.plays).toBe(pooled.plays);
    expect(before.plays).toBe(262); // unchanged — the before arm did not grow
    expect(before.neitherReaches).toBe(56); // unchanged
    // [session 89] 56 -> 62. The pooled figure used to EQUAL the before arm's,
    // which was the whole point of this test: the residual sat entirely in the
    // before era. It no longer does — today's era now contributes 6 of its own,
    // and that is the same six as the retraction above. The partition assertion
    // on the first line is what still holds unconditionally.
    expect(pooled.neitherReaches).toBe(68);  /* [session 91] was 62 */
    expect(pooled.neitherReaches - before.neitherReaches).toBe(today.neitherReaches);
  });

  it("reports the rescue rate as an INTERVAL, because 15/15 is not 100%", () => {
    const r = redrawCounterfactual(split.today);
    // ⚠ [session 89] STRUCTURAL CHANGE 4. This was 15/15 — an interval whose
    // upper bound sat exactly at 1 because no dead hand had ever failed to be
    // rescued. It is now 26 of 32, and the interval no longer touches either
    // end. The instruction that produced the old pin ("15/15 is not 100%") is
    // now enforced by the data rather than only by the test.
    const dead = r.rescue + r.neitherReaches;
    expect(dead).toBe(42); // was 15  /* [session 91] was 32 */
    expect(r.rescue).toBe(30);  /* [session 91] was 26 */
    // [session 91] The point estimate keeps falling on every growth:
    // **15/15 (100%) -> 26/32 (81.3%) -> 30/42 (71.4%).** Same monotone shape
    // as the ratio above and the same reading — the redraw's rescue power was
    // never as high as the first small sample said. The interval is re-pinned
    // to what the data now reads, and the trend is stated so the next reader
    // sees a sequence rather than a single number.
    const [lo, hi] = wilson(r.rescue, dead);
    expect(lo).toBeGreaterThan(0.56); // [session 91] was > 0.64, was > 0.78
    expect(lo).toBeLessThan(0.57);
    expect(hi).toBeGreaterThan(0.82); // [session 91] was > 0.91, was exactly 1
    expect(hi).toBeLessThan(0.83);
  });

  it("wilson degrades sanely at the edges", () => {
    expect(wilson(0, 0)).toEqual([0, 1]);
    const [lo, hi] = wilson(1, 2);
    expect(lo).toBeGreaterThan(0);
    expect(hi).toBeLessThan(1);
  });
});

describe("GATE 2 — the collapse, decomposed", () => {
  const d = budgetZeroDecomposition(traces, created);

  it("splits into three terms that sum to the observed drop", () => {
    expect(d.beforeRate).toBeCloseTo(0.449, 3); // unchanged
    expect(d.standardisedRate).toBeCloseTo(0.417, 3); // [session 91] was 0.410
    expect(d.noRestoreRate).toBeCloseTo(0.24926686217008798, 3); // was 0.213  /* [session 91] was 0.228 */
    expect(d.todayRate).toBeCloseTo(0.11436950146627566, 3); // was 0.0149  /* [session 91] was 0.0692 */
    expect(d.lengthTerm + d.pacingTerm + d.oilTerm).toBeCloseTo(d.beforeRate - d.todayRate, 10);
  });

  it("says cast length explains only ~3.9pp of ~38pp — the drop is WITHIN length", () => {
    // [session 89] 0.054 -> 0.0385, and the drop it is a share of shrank from
    // ~43pp to ~38pp. The conclusion is UNCHANGED and slightly stronger: length
    // now accounts for 10.2% of the drop, against 12.5% before, so the
    // `< 15%` bound holds with more room than it did.
    expect(d.lengthTerm).toBeCloseTo(0.031413267211851115, 3);  /* [session 91] was 0.0385 */
    expect(d.lengthTerm).toBeLessThan(0.15 * (d.beforeRate - d.todayRate));
  });

  it("standardises every today play — no stratum silently becomes a zero", () => {
    expect(d.unmatchedPlays).toBe(0);
  });

  it("validates the no-restore counterfactual on the before era, which fired no oils", () => {
    const cf = split.before.reduce((s, t) => s + budgetZeroPlaysWithoutRestore(t), 0);
    const obs = split.before.reduce((s, t) => s + budgetZeroPlays(t), 0);
    // Both UNCHANGED — the before era did not grow, which is what makes it
    // usable as a control at all.
    expect(obs).toBe(184);
    expect(cf).toBe(183);
    // The one difference is the single before-era cast that opened at focusMeter 2
    // rather than 3 — a real feature of the corpus, not slack in the method.
    expect(split.before.filter((t) => t.turns[0]!.focusMeter !== FOCUS_POOL).length).toBe(1);
  });

  it("isolates the PACING term on the 59 restore-free casts, where the oil cannot be the cause", () => {
    // [session 89] 41 -> 59 restore-free casts; [115, 2] -> [190, 18]. The
    // observed no-oil rate went 1.7% -> 9.5%, so the pacing gap narrowed from
    // (27.8% vs 1.7%) to (33.6% vs 9.5%) — still a large unexplained gap, and
    // still one the oil cannot account for, which is this test's only claim.
    const noOil = split.today.filter((t) => !firedOil(t));
    expect(noOil.length).toBe(69);  /* [session 91] was 59 */
    const plays = noOil.reduce((s, t) => s + playCount(t), 0);
    const zero = noOil.reduce((s, t) => s + budgetZeroPlays(t), 0);
    expect([plays, zero]).toEqual([242, 37]); // [session 91] was [190, 18]
    expect(standardise(split.before, noOil).rate).toBeCloseTo(0.36200642791551885, 3); // was 0.278  /* [session 91] was 0.336 */
    // No restore ever fired here, so the counterfactual equals the observation.
    // That is the self-check; the result is the gap to 27.8%.
    expect(noOil.reduce((s, t) => s + budgetZeroPlaysWithoutRestore(t), 0)).toBe(zero);
  });

  it("isolates the OIL term on the 13 oil casts, which revert to the old regime without it", () => {
    // [session 89] 13 -> 15 oil casts, 21 -> 24 oils, [87,1,41] -> [99,2,48].
    const oiled = split.today.filter(firedOil);
    expect(oiled.length).toBe(15);
    expect(oiled.reduce((s, t) => s + oilsConsumed(t), 0)).toBe(24);
    const plays = oiled.reduce((s, t) => s + playCount(t), 0);
    const zero = oiled.reduce((s, t) => s + budgetZeroPlays(t), 0);
    const cf = oiled.reduce((s, t) => s + budgetZeroPlaysWithoutRestore(t), 0);
    expect([plays, zero, cf]).toEqual([99, 2, 48]);
    // 48.5% stripped (was 47.1%), against a before-era length-standardised
    // 55.3% (was 54.9%). This is the STEADIEST result in the file: strip the
    // restores and the oil casts revert to within 7pp of the old regime, the
    // same finding at both corpus sizes.
    expect(cf / plays).toBeCloseTo(0.485, 3);
    expect(standardise(split.before, oiled).rate).toBeCloseTo(0.553, 3);
  });

  it("detects oils on consumablesUsed, NOT on the focus meter — they give different answers", () => {
    // castTrace.ts skips the `use_fishing_item` response, so a meter jump seen
    // across two real turns is `restore minus the move spent on the same
    // transition`. Detecting on the meter finds 11 casts; the truth is 13.
    const meterDetected = traces.filter((t) => {
      for (let i = 1; i < t.turns.length; i++) if (t.turns[i]!.focusMeter > t.turns[i - 1]!.focusMeter) return true;
      return false;
    });
    // [session 89] 11 -> 13 and 13 -> 15. The GAP is still exactly 2, which is
    // the point: meter detection under-counts by a fixed mechanism, not a rate.
    expect(meterDetected.length).toBe(13);
    expect(traces.filter(firedOil).length).toBe(15);
  });

  it("rules the GEAR out: the decks changed a great deal and their reach did not", () => {
    const reach = (ts: readonly import("../../src/sim/fishing/castTrace.js").CastTrace[]) =>
      ts.reduce((s, t) => s + deckIntrinsicReach(t), 0) / ts.length;
    const crit = (ts: readonly import("../../src/sim/fishing/castTrace.js").CastTrace[]) =>
      ts.reduce((s, t) => s + deckCritFraction(t), 0) / ts.length;
    // [session 89] today's reach 0.151 -> 0.153, so the two arms now agree to
    // 0.00003 rather than 0.002 — the GEAR null got STRONGER on more data.
    expect(reach(split.before)).toBeCloseTo(0.153, 3);
    expect(reach(split.today)).toBeCloseTo(0.153, 3);
    expect(Math.abs(reach(split.before) - reach(split.today))).toBeLessThan(0.01);
    // Meanwhile the decks really did change, which is what makes the null
    // informative. [session 89] today's crit fraction 0.342 -> 0.314 — still
    // far from the before era's 0.185, so the contrast holds.
    expect(crit(split.before)).toBeCloseTo(0.185, 3);
    expect(crit(split.today)).toBeCloseTo(0.30916895338473155, 3);  /* [session 91] was 0.314 */
  });

  it("fires the before-era-is-oil-free assertion if that control ever stops holding", () => {
    const fake = new Map(created);
    // Re-date one oil cast into the before era: the control is now contaminated.
    const oiled = split.today.find(firedOil)!;
    fake.set(oiled.docId, "2026-08-19T00:00:00.000Z");
    expect(() => assertCastEraSound(traces, fake)).toThrow(/before-era cast\(s\) fired an oil/);
  });
});

/**
 * Not part of either gate — the brief's "do if there is room" item. It is
 * pinned anyway because it is the input QUESTIONS.md §26's shadow design rests
 * on, and an unpinned input to a design decision is how the +19.40pp figure
 * happened.
 */
describe("§3's heldCoverage signal, re-run per era", () => {
  it("SURVIVES the split — the dead hands changed, the separation did not", () => {
    const pooled = separability(redrawCounterfactual(traces));
    const today = separability(redrawCounterfactual(split.today));
    // [session 89] pooled 0.922 -> 0.921, today 0.907 -> 0.925. The signal
    // SURVIVES a corpus 14% larger and today's era 37% larger — which is what
    // this test's title claims and is now better evidenced than it was.
    expect(pooled.coverageAuc).toBeCloseTo(0.9216452205882353, 3);  /* [session 91] was 0.921 */
    expect(today.coverageAuc).toBeCloseTo(0.927058668771376, 3);  /* [session 91] was 0.925 */
    // The dead hands today are a DIFFERENT population, not a smaller version of
    // the old one: their mean coverage nearly doubles once the budget-0 hands
    // (which could barely cover anything, being frozen on one cell) are gone.
    // [session 89] pooled 5.13 -> 5.25, today 8.87 -> 7.31. The doubling claim
    // softens to ~1.4x but its direction and its cause are unchanged.
    expect(pooled.meanCoverageDead).toBeCloseTo(5.2578125, 2);  /* [session 91] was 5.25 */
    expect(today.meanCoverageDead).toBeCloseTo(6.857142857142857, 2);  /* [session 91] was 7.31 */
    expect(today.meanCoverageDead).toBeGreaterThan(pooled.meanCoverageDead);
    expect(today.deadPlays).toBe(42); // was 15  /* [session 91] was 32 */
    expect(today.livePlays).toBe(181); // was 112  /* [session 91] was 150 */
  });

  it("RETRACTS `wasted` being structurally zero — it follows neither = 0, and neither is not 0", () => {
    // ⚠ [session 89] STRUCTURAL CHANGE 3, and it is change 2 restated. `wasted`
    // counts a redraw that fires on a hand no redraw could have saved, so it is
    // zero exactly when `neitherReaches` is zero. Today's era now has six such
    // hands, and `wasted` takes 0, 3, 4, 5 and 6 across the sweep.
    //
    // **What this costs, stated plainly rather than buried in a number.** The
    // old pin supported an argument: with `wasted` structurally zero, the only
    // trade a threshold makes is rescues against sacrifices, so the trigger's
    // job is DETECTION rather than SELECTION. That argument no longer holds —
    // a threshold can now also spend mana on hands nothing could rescue, which
    // is precisely a selection cost. It is retracted here rather than in a
    // recap, because this test is where it was asserted.
    const today = separability(redrawCounterfactual(split.today));
    const wasted = [...new Set(today.sweep.map((r) => r.wasted))].sort((a, b) => a - b);
    // [session 91] The set widened again, [0,3,4,5,6] -> [0,3,6,7,9,10,11,12].
    // Same direction as session 89's retraction and further along it: the
    // selection cost this pin exists to record is growing, not stabilising.
    expect(wasted).toEqual([0, 3, 6, 7, 9, 10, 11, 12]);
    expect(today.sweep.some((r) => r.wasted > 0)).toBe(true);
    // The ceiling is `neitherReaches` by construction: a threshold cannot waste
    // a redraw on a hand that was never unrescuable. Asserting the identity
    // rather than the number keeps the two facts tied together.
    expect(Math.max(...today.sweep.map((r) => r.wasted))).toBe(
      redrawCounterfactual(split.today).neitherReaches,
    );
    const k7 = today.sweep.find((r) => r.threshold === 7)!;
    expect([k7.fires, k7.rescues, k7.sacrifices, k7.manaSpent]).toEqual([38, 17, 3, 61]); // [session 91] was [27, 13, 1, 43]
  });
});

/**
 * [session 85, brief §1 / GATE 1] The overspend control.
 *
 * Session 84 left the collapse's proximate mechanism as one number — first-play
 * spend 1.553 -> 0.852 — which cannot tell *the fish got easier to reach* from
 * *the bot aimed more cheaply*. These pin the second half.
 *
 * ⚠ Read the ORACLE caveat in `openingOverspend`'s docblock before quoting any
 * of these figures. `optimal` uses the cell the fish actually resolved on, so
 * neither arm's LEVEL is a policy target; only the era COMPARISON is sound, and
 * it is sound precisely because the same oracle lens is applied to both.
 *
 * Unlike session 84's play counts — which failed to reproduce the brief three
 * briefs running — every §1 figure here landed on the first run with no
 * predicate search. That is recorded because it is the evidence that the
 * measurement is the brief's, not a near-miss reconstruction of it.
 */
describe("§1 / GATE 1 — the bot stopped OVERSHOOTING; the target never moved", () => {
  const over = openingOverspendSplit(traces, created);

  it("pins the shared origin the whole control rests on: 147 of 147 RECORDED openings at (2,2)", () => {
    // The claim is stronger than the brief's "147 of 148" and its exception has
    // ONE cause, not two. See `assertOpeningFocusPinned`'s docblock.
    expect(() => assertOpeningFocusPinned(traces)).not.toThrow();
    // [session 89] 147 -> 167 of 168. The exception is still the SAME single
    // cast, which is the claim: twenty more casts produced no new one.
    expect(traces.filter((t) => t.hasStart).length).toBe(177);  /* [session 91] was 167 */
    const unrecorded = traces.filter((t) => !t.hasStart);
    expect(unrecorded).toHaveLength(1);
    expect(unrecorded[0]!.docId).toBe("12975152");
    // Its turn 0 is a MID-CAST RESUME, which is why it opens at (3,2) with a
    // partly-spent meter and a one-card hand...
    expect(unrecorded[0]!.turns[0]!.focusPoint).toEqual({ x: 3, y: 2 });
    expect(unrecorded[0]!.turns[0]!.focusMeter).toBe(2);
    expect(unrecorded[0]!.turns[0]!.play).not.toBeNull();
    // ...and it is ALSO the corpus's only cast with no covering focus at all.
    // One cause, two apparent anomalies.
    expect(openingOverspend(unrecorded[0]!, created)!.optimal).toBeNull();
    expect(over.rows.filter((r) => r.optimal === null)).toHaveLength(1);
  });

  it("reproduces the brief's table cell for cell — and the optimal move is UNCHANGED", () => {
    expect([over.before.casts, over.today.casts]).toEqual([94, 84]); // [session 91] was [94, 74]

    // The hands did not get wider. [session 89] today 7.20 -> 7.11, moving
    // slightly FURTHER from the before era rather than toward it.
    expect(over.before.meanHandFootprint).toBeCloseTo(7.38, 2);
    expect(over.today.meanHandFootprint).toBeCloseTo(7.178571428571429, 2);  /* [session 91] was 7.11 */

    // What the bot spent — and it must reproduce `focusEraSplit`'s own figure
    // rather than merely resemble it, which is what the shared first-play
    // predicate buys.
    expect(over.before.meanActual).toBeCloseTo(1.553, 3);
    expect(over.today.meanActual).toBeCloseTo(0.8214285714285714, 3); // was 0.852  /* [session 91] was 0.838 */
    const eras = focusEraSplit(traces, created);
    expect(over.before.meanActual).toBeCloseTo(eras.before.meanFirstPlaySpend, 10);
    expect(over.today.meanActual).toBeCloseTo(eras.today.meanFirstPlaySpend, 10);

    /* =====================================================================
     * ⚠⚠⚠ [session 91] THE CONTROL BROKE. THIS ASSERTION IS RED ON PURPOSE.
     *     DO NOT WIDEN THE BOUND.
     * =====================================================================
     *
     * Session 89 called this "the single most important thing in the file that
     * did NOT move", and it has now moved. Across session 91's ten-cast batch
     * `today.meanOptimal` went **0.662 -> 0.631** while `before` is frozen at
     * 0.656, so the two arms now differ by **0.0250 against a 0.01 bound**.
     *
     * ## Why this is not a number to bump
     *
     * The bound is load-bearing for the section's conclusion. The argument is:
     * the cheapest move that COULD have worked is the same in both eras, so
     * the eras do not differ in difficulty, so **the entire difference is
     * OVERSPEND** (asserted immediately below). That syllogism needs the two
     * `meanOptimal`s to agree. At 0.025 apart on a quantity whose era gap is
     * 0.897 vs 0.176 the conclusion is not overturned — but the control is no
     * longer controlling, and widening the bound to 0.03 would convert a
     * falsified premise into a passing test, which is the exact move session
     * 90 refused on `damageEconomy.test.ts` and CLAUDE.md rule 9 forbids.
     *
     * ## It is the THIRD claim in this file moving the same way this session
     *
     * The budget-zero ratio (~30x -> 6.5x -> 3.9x), the redraw rescue rate
     * (100% -> 81% -> 71%) and now this. All three degrade monotonically as
     * "today's era" fills with ordinary play, and all three were first pinned
     * when that era was small. That is a pattern about the ERA PREDICATE, not
     * three independent coincidences, and it wants a ruling rather than three
     * more bumps. **`QUESTIONS.md` §32 asks for it.** Until it comes, this
     * stays red.
     * ===================================================================== */
    expect(over.before.meanOptimal).toBeCloseTo(0.656, 3);
    expect(over.today.meanOptimal).toBeCloseTo(0.631, 3); // [session 91] was 0.662
    expect(Math.abs(over.before.meanOptimal - over.today.meanOptimal)).toBeLessThan(0.01);

    // So the entire difference is OVERSPEND. [session 89] today 0.204 -> 0.176.
    expect(over.before.overspend).toBeCloseTo(0.897, 3);
    expect(over.today.overspend).toBeCloseTo(0.176, 3);
  });

  it("matches on the whole optimal DISTRIBUTION, not just its mean", () => {
    // A mean can agree while the shapes differ, and "the target never moved" is
    // a claim about the distribution. Before: 41/43/9. Today: 33/33/8.
    // [session 89] today was 26/21/7 over 54 casts; the SHAPE is what matters
    // and it is unchanged — the before arm normalises to 44/46/10% and today's
    // to 45/45/11%, against 48/39/13% at the old size. It got closer.
    expect([...over.before.optimalHistogram.entries()].sort()).toEqual([[0, 41], [1, 43], [2, 9]]);
    expect([...over.today.optimalHistogram.entries()].sort()).toEqual([[0, 40], [1, 35], [2, 9]]); // [session 91] was [[0,33],[1,33],[2,8]]
    // The ACTUAL distributions, by contrast, are nothing alike — and the tell
    // is the tail: 17 before-era casts spent the WHOLE meter on move one, and
    // today's era has no such cast at all.
    expect([...over.before.actualHistogram.entries()].sort()).toEqual([[0, 12], [1, 35], [2, 30], [3, 17]]);
    // [session 89] today 21/20/13 -> 30/26/18, and the tell SURVIVES: still not
    // one cast in 74 that spent the whole meter on move one.
    // [session 91] -> 34/31/19, and the tell SURVIVES a third time: still not
    // one cast in 84 that spent the whole meter on move one.
    expect([...over.today.actualHistogram.entries()].sort()).toEqual([[0, 34], [1, 31], [2, 19]]);
    expect(over.today.actualHistogram.get(3) ?? 0).toBe(0);
  });

  it("§1a — the series STEPS, it does not trend, which is what bears on the cause", () => {
    const days = openingOverspendByDay(over.rows);
    const byDay = new Map(days.map((d) => [d.day, d]));
    const at = (d: string): number => byDay.get(d)!.overspend;

    expect(at("2026-08-15")).toBeCloseTo(1.0, 2);
    expect(at("2026-08-16")).toBeCloseTo(0.8, 2);
    expect(at("2026-08-17")).toBeCloseTo(1.15, 2);
    expect(at("2026-08-19")).toBeCloseTo(0.84, 2);
    expect(at("2026-08-20")).toBeCloseTo(-0.4, 2);
    expect(at("2026-08-21")).toBeCloseTo(0.1, 2);
    expect(at("2026-08-22")).toBeCloseTo(0.25, 2);
    expect(at("2026-08-23")).toBeCloseTo(0.5, 2);

    // 08-18 is the unscored single cast — the resumed one above. It carries no
    // overspend because it has no optimal, and NaN is the honest value.
    expect(byDay.get("2026-08-18")!.n).toBe(1);
    expect(byDay.get("2026-08-18")!.scored).toBe(0);
    expect(Number.isNaN(byDay.get("2026-08-18")!.overspend)).toBe(true);

    // ⚠ THE DATING CAVEAT, pinned so it cannot be lost: the 08-20 casts already
    // read the NEW regime, and they are stamped BEFORE sessions 61/62's
    // commits. So the 20.3h empty gap is NOT a clean bracket, and a session
    // spent replaying those two commits may be replaying the wrong side of the
    // change. n=5 — a caveat, not a result.
    expect(byDay.get("2026-08-20")!.n).toBe(5);
    expect(at("2026-08-20")).toBeLessThan(at("2026-08-19"));

    // And inside today's era it drifts back UP rather than continuing down,
    // which is what argues against a still-sharpening learned model.
    expect(at("2026-08-21")).toBeLessThan(at("2026-08-22"));
    expect(at("2026-08-22")).toBeLessThan(at("2026-08-23"));

    // [session 89] A NEW DAY, and it cuts against the monotone reading above.
    // 08-24 (session 87's twenty casts) comes in at 0.10 — back to 08-21's
    // level, after the 0.10 -> 0.25 -> 0.50 climb. So the series inside today's
    // era does not trend in EITHER direction; it wanders in a band roughly
    // [0.1, 0.5] while the before era sat near 1.0. The band separation is the
    // durable claim; the within-era climb was four points of noise, and this
    // is exactly the drift the file exists to make visible.
    expect(byDay.get("2026-08-24")!.n).toBe(30);  /* [session 91] was 20 */
    expect(at("2026-08-24")).toBeCloseTo(0.16666666666666674, 2);  /* [session 91] was 0.1 */
    expect(at("2026-08-24")).toBeLessThan(at("2026-08-23"));
    for (const day of ["2026-08-21", "2026-08-22", "2026-08-23", "2026-08-24"]) {
      expect(at(day)).toBeLessThan(at("2026-08-19"));
    }
  });
});
